name: npm-test
on:
  workflow_dispatch:
  pull_request:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.0
      - name: install npm packages
        run: npm ci
        working-directory: ./apps
      - name: npm test
        run: npm test
        working-directory: ./apps
